### ISSUE TITLE
Update to the latest Julia and fix builds

### ISSUE THREAD

**Issue by XVilka** [vonDonnerstein/QuantumLab.jl#14]
It doesn't work as is right now.

See also https://discourse.julialang.org/t/is-quantumlab-jl-abandoned/33136

**Comment by vonDonnerstein** [comment]
Just published on the new Registry with all fixes included. Please test if it works for you and let me know if you encounter any further problems.

**Comment by vonDonnerstein** [comment]
Closing for now. Feel free to open another issue if you run into anything.
